name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build day25
      working-directory: ./rust/day25
      run: cargo build --verbose
    - name: Run tests day25
      working-directory: ./rust/day25
      run: cargo test --verbose
