name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build day13
      working-directory: ./rust/day13
      run: cargo build --verbose
    - name: Run tests day13
      working-directory: ./rust/day13
      run: cargo test --verbose
